# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics-misc
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  misc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED

          # Options
          user: deepencoding
          template: classic
          base: ""
          config_timezone: Asia/Calcutta
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_source: https://deepencoding.hashnode.dev/rss.xml
